namespace Framework.Netcode;

/// <summary>
/// Packet opcode/type maps generated by PacketGen through this partial marker type.
/// </summary>
[PacketRegistry]
public partial class PacketRegistry
{
}
